//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by HexCtrl.rc
//
#define IDB_HEXCTRL_ICON                3000
#define IDB_HEXCTRL_MENU_COPY           3001
#define IDB_HEXCTRL_MENU_PASTE          3002
#define IDB_HEXCTRL_SCROLL_V            3003
#define IDB_HEXCTRL_SCROLL_H            3004

#define IDD_HEXCTRL_SEARCH              5101
#define IDD_HEXCTRL_ABOUT               5102
#define IDC_HEXCTRL_SEARCH_BUTTON_SEARCH_F 6001
#define IDC_HEXCTRL_SEARCH_BUTTON_SEARCH_B 6002
#define IDC_HEXCTRL_SEARCH_RADIO_HEX    6003
#define IDC_HEXCTRL_SEARCH_RADIO_ASCII  6004
#define IDC_HEXCTRL_SEARCH_RADIO_UNICODE 6005
#define IDC_HEXCTRL_SEARCH_STATIC_TEXTBOTTOM 6006
#define IDC_HEXCTRL_SEARCH_EDITSEARCH   6007
#define IDC_HEXCTRL_ABOUT_STATIC_LINKGITHUB 6008
#define IDC_HEXCTRL_ABOUT_STATIC_VERSION 6009

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        125
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1013
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
