//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by HexCtrl.rc
//
#define IDB_HEXCTRL_ICON                9001
#define IDB_HEXCTRL_MENU_COPY           9002
#define IDB_HEXCTRL_MENU_PASTE          9003
#define IDB_HEXCTRL_MENU_FILL_ZEROS     9004
#define IDB_HEXCTRL_SCROLL_V            9005
#define IDB_HEXCTRL_SCROLL_H            9006
#define IDD_HEXCTRL_SEARCH              9101
#define IDD_HEXCTRL_ABOUT               9102
#define IDC_HEXCTRL_SEARCH_BUTTON_SEARCH_F 9201
#define IDC_HEXCTRL_SEARCH_BUTTON_SEARCH_B 9202
#define IDC_HEXCTRL_SEARCH_RADIO_HEX    9203
#define IDC_HEXCTRL_SEARCH_RADIO_ASCII  9204
#define IDC_HEXCTRL_SEARCH_RADIO_UNICODE 9205
#define IDC_HEXCTRL_SEARCH_STATIC_TEXTBOTTOM 9206
#define IDC_HEXCTRL_SEARCH_EDIT_SEARCH  9207
#define IDC_HEXCTRL_SEARCH_EDIT_REPLACE 9208
#define IDC_HEXCTRL_SEARCH_BUTTON_REPLACE 9209
#define IDC_HEXCTRL_SEARCH_BUTTON_REPLACE_ALL 9210
#define IDC_HEXCTRL_ABOUT_STATIC_VERSION 9211
#define IDC_HEXCTRL_ABOUT_LINKGITHUB    9212
#define IDR_HEXCTRL_MENU                9214
#define IDM_HEXCTRL_MAIN_SEARCH         32769
#define IDM_HEXCTRL_MAIN_SHOWAS         32770
#define IDM_HEXCTRL_SHOWAS_BYTE         32771
#define IDM_HEXCTRL_SHOWAS_WORD         32772
#define IDM_HEXCTRL_SHOWAS_DWORD        32773
#define IDM_HEXCTRL_SHOWAS_QWORD        32774
#define IDM_HEXCTRL_BOOKMARKS_ADD       32775
#define IDM_HEXCTRL_BOOKMARKS_REMOVE    32776
#define IDM_HEXCTRL_BOOKMARKS_NEXT      32777
#define IDM_HEXCTRL_BOOKMARKS_PREV      32778
#define IDM_HEXCTRL_BOOKMARKS_CLEARALL  32779
#define IDM_HEXCTRL_CLIPBOARD_COPY_HEX  32780
#define IDM_HEXCTRL_MAIN_UNDO           32781
#define IDM_HEXCTRL_MAIN_REDO           32782
#define IDM_HEXCTRL_MAIN_FILL_ZEROS     32783
#define IDM_HEXCTRL_MAIN_SELECT_ALL     32784
#define IDM_HEXCTRL_MAIN_ABOUT          32785
#define IDM_HEXCTRL_CLIPBOARD_COPY_HEX_LE 32786
#define IDM_HEXCTRL_CLIPBOARD_COPY_HEX_FORMATTED 32787
#define IDM_HEXCTRL_CLIPBOARD_COPY_ASCII 32788
#define IDM_HEXCTRL_CLIPBOARD_COPY_BASE64 32789
#define IDM_HEXCTRL_CLIPBOARD_PASTE_HEX 32790
#define IDM_HEXCTRL_CLIPBOARD_PASTE_ASCII 32791
#define IDM_HEXCTRL_APPEARANCE_FONT_INCREASE 32792
#define IDM_HEXCTRL_APPEARANCE_FONT_DECREASE 32793
#define IDM_HEXCTRL_APPEARANCE_CAPACITY_INCREASE 32794
#define IDM_HEXCTRL_APPEARANCE_CAPACITY_DECREASE 32795

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        9215
#define _APS_NEXT_COMMAND_VALUE         32797
#define _APS_NEXT_CONTROL_VALUE         9214
#define _APS_NEXT_SYMED_VALUE           9333
#endif
#endif
